# Generated by Django 4.2.9 on 2024-05-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(max_length=200, null=True)),
                ('ProjectType', models.CharField(max_length=200, null=True)),
                ('DueDate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
