# Generated by Django 4.2.9 on 2024-05-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(max_length=200, null=True)),
                ('Status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Pending', 'Pending'), ('Testing', 'Testing'), ('Bug', 'Bug')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskName', models.CharField(max_length=200, null=True)),
                ('TaskDescription', models.CharField(max_length=1500, null=True)),
                ('TaskType', models.CharField(choices=[('Design', 'Desgin'), ('Testing', 'Testing'), ('Development', 'Development'), ('Deployement', 'Deployement')], max_length=200, null=True)),
                ('TaskAssignTo', models.CharField(choices=[('Hamza', 'Hamza'), ('Adil', 'Adil'), ('Usama', 'Usama')], max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='projects',
            name='DueDate',
            field=models.DateTimeField(null=True),
        ),
    ]
