# Generated by Django 4.2.9 on 2024-05-23 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_status_task_alter_projects_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.projects'),
        ),
        migrations.AddField(
            model_name='status',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.task'),
        ),
    ]
