# Generated by Django 4.2.9 on 2024-05-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_status_project_status_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='status',
            name='tags',
            field=models.ManyToManyField(to='accounts.tags'),
        ),
    ]
