# Generated by Django 4.2.9 on 2024-05-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tags_status_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='tags',
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(to='accounts.tags'),
        ),
    ]
