# Generated by Django 4.2.9 on 2024-05-23 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_status_tags_task_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='ProjectName',
            new_name='Technology',
        ),
    ]
