# Generated by Django 4.2.9 on 2024-05-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_projectname_tags_technology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='ProjectName',
        ),
        migrations.AddField(
            model_name='status',
            name='CurrentDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='Due_Date',
            field=models.DateField(null=True),
        ),
    ]
