# Generated by Django 4.2.9 on 2024-05-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_task_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='SelectStatus',
            field=models.CharField(choices=[('ToDo', 'ToDO'), ('In Progress', 'In Progress'), ('Testing', 'Testing'), ('Bug', 'Bug'), ('Completed', 'Completed')], max_length=200, null=True),
        ),
    ]
