# Generated by Django 4.2.9 on 2024-05-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_tasks_selectstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='DueDate',
            field=models.DateTimeField(null=True),
        ),
    ]
