# Generated by Django 4.2.9 on 2024-05-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_tasks_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
