# Generated by Django 4.2.9 on 2024-06-03 11:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0014_remove_tasks_user_tasks_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='user',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
