# Generated by Django 4.2.9 on 2024-06-04 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_projects_user_remove_customers_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='CurrentDate',
        ),
        migrations.RemoveField(
            model_name='status',
            name='Due_Date',
        ),
        migrations.RemoveField(
            model_name='status',
            name='project',
        ),
        migrations.RemoveField(
            model_name='status',
            name='task',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='TaskAssignTo',
        ),
        migrations.AddField(
            model_name='status',
            name='Assign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customers'),
        ),
    ]
