# Generated by Django 4.2.9 on 2024-06-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_status_currentdate_remove_status_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='DueDate',
            field=models.DateField(null=True),
        ),
    ]
