# Generated by Django 4.2.9 on 2024-06-04 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_tasks_duedate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='employee',
            new_name='user',
        ),
    ]
