# Generated by Django 4.2.9 on 2024-06-04 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_rename_employee_tasks_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='user',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='user',
            new_name='employee',
        ),
    ]
