# Generated by Django 4.2.9 on 2024-06-04 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_customers_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='employee',
            new_name='user',
        ),
    ]
