# Generated by Django 4.2.9 on 2024-06-04 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0028_remove_tasks_employee_tasks_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='user',
        ),
        migrations.AddField(
            model_name='customers',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
