# Generated by Django 4.2.9 on 2024-06-04 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_remove_tasks_employee_remove_customers_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='employe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customers'),
        ),
    ]
