# Generated by Django 4.2.9 on 2024-06-04 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_remove_customers_user_alter_tasks_employe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='employe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customers'),
        ),
    ]
