# Generated by Django 4.2.9 on 2024-06-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_tasks_employe'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='tasks',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='tasks',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='SelectStatus',
            field=models.CharField(choices=[('ToDo', 'ToDO'), ('In Progress', 'In Progress'), ('Testing', 'Testing'), ('Bug', 'Bug'), ('Completed', 'Completed')], default='ToDo', max_length=200, null=True),
        ),
    ]
