# Generated by Django 4.2.9 on 2024-06-07 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0034_customers_profile_pic_tasks_image_tasks_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='Comments',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='profile_pic',
            field=models.ImageField(blank=True, default='icon1', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customers',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='status',
            name='Status',
            field=models.CharField(choices=[('ToDo', 'ToDo'), ('In Progress', 'In Progress'), ('Pending', 'Pending'), ('Testing', 'Testing'), ('Bug', 'Bug')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
