# Generated by Django 4.2.9 on 2024-06-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='Assign',
            field=models.ManyToManyField(null=True, to='accounts.customers'),
        ),
    ]
