# Generated by Django 4.2.9 on 2024-06-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alter_tasks_taskdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='ImageURL',
            field=models.URLField(null=True),
        ),
    ]
