# Generated by Django 4.2.9 on 2024-06-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='task',
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='Comments',
            field=models.CharField(default='0', max_length=200, null=True),
        ),
    ]
